#!/usr/bin/env python3
"""Generate schema-driven artifacts from the OpenDental documentation XML.

Output:
  seed/00-schema.sql
    - full CREATE TABLE statements for the demo database, mirroring the real
      25-4 schema so demo and production take the identical write path.
      (The API itself introspects the live database at runtime via
      information_schema, so it adapts to 24-3 / 25-4 automatically; this
      generated DDL is only for the docker demo profile.)

Re-run after an OpenDental upgrade:
  python3 tools/schema-gen/generate_schema.py docs/schema/OpenDentalDocumentation25-4.xml

The table list below is every table the sidecar reads or writes.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

TABLES = [
    "adjustment", "appointment", "appointmenttype", "carrier", "claim",
    "claimpayment", "claimproc", "clinic", "commlog", "definition",
    "feesched", "insplan", "inssub", "operatory", "patient", "patientnote",
    "patplan", "payment", "paysplit", "procedurecode", "procedurelog",
    "provider", "recall", "recalltype", "schedule", "scheduleop", "signalod",
]

REPO_ROOT = Path(__file__).resolve().parents[2]
SQL_OUT = REPO_ROOT / "seed/00-schema.sql"


def classify(mysql_type: str) -> str:
    """Map a MySQL column type from the XML to a builder 'kind'."""
    t = mysql_type.lower()
    if t.startswith("timestamp"):
        return "Timestamp"
    if t.startswith("datetime"):
        return "DateTime"
    if t.startswith("date"):
        return "Date"
    if t.startswith("time"):
        return "Time"
    if t.startswith(("varchar", "char", "text", "mediumtext", "longtext", "tinytext", "blob", "mediumblob", "longblob", "varbinary")):
        return "String"
    if t.startswith(("double", "float", "decimal")):
        return "Float"
    if t.startswith(("bigint", "int", "tinyint", "smallint", "mediumint")):
        return "Int"
    raise ValueError(f"Unmapped MySQL type: {mysql_type}")


def sql_default(kind: str) -> str:
    return {
        "Int": "0",
        "Float": "0",
        "Date": "'0001-01-01'",
        "DateTime": "'0001-01-01 00:00:00'",
        "Time": "'00:00:00'",
    }[kind]


def main(xml_path: str) -> None:
    root = ET.parse(xml_path).getroot()
    version = root.get("version", "unknown")
    schema = {}
    for t in root.findall("table"):
        name = t.get("name")
        if name not in TABLES:
            continue
        cols = []
        for c in t.findall("column"):
            cols.append((int(c.get("order")), c.get("name"), c.get("type")))
        cols.sort()
        schema[name] = [(n, ty) for _, n, ty in cols]

    missing = [t for t in TABLES if t not in schema]
    if missing:
        sys.exit(f"Tables not found in XML: {missing}")

    # ── Demo schema SQL ─────────────────────────────────────────
    sql = [
        f"-- Generated by tools/schema-gen/generate_schema.py from OpenDental schema {version}.",
        "-- Full table definitions so the demo database accepts the same full-column",
        "-- INSERTs the API issues against a real OpenDental database.",
        "-- Do not edit by hand.",
        "",
    ]
    for name, cols in schema.items():
        sql.append(f"CREATE TABLE IF NOT EXISTS {name} (")
        defs = []
        for i, (cname, ctype) in enumerate(cols):
            ctype_clean = re.sub(r"\(\d+\)$", "", ctype) if ctype.lower().startswith(("bigint", "tinyint", "smallint", "int", "mediumint")) else ctype
            if i == 0:
                defs.append(f"  {cname} {ctype_clean} NOT NULL AUTO_INCREMENT")
                continue
            kind = classify(ctype)
            if kind == "Timestamp":
                defs.append(f"  {cname} timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
            elif kind == "String":
                # TEXT/BLOB can't take literal defaults portably; allow NULL.
                if ctype.lower().startswith(("text", "mediumtext", "longtext", "tinytext", "blob", "mediumblob", "longblob")):
                    defs.append(f"  {cname} {ctype_clean}")
                else:
                    defs.append(f"  {cname} {ctype_clean} NOT NULL DEFAULT ''")
            else:
                defs.append(f"  {cname} {ctype_clean} NOT NULL DEFAULT {sql_default(kind)}")
        defs.append(f"  PRIMARY KEY ({cols[0][0]})")
        sql.append(",\n".join(defs))
        sql.append(");")
        sql.append("")
    SQL_OUT.write_text("\n".join(sql))

    total_cols = sum(len(c) for c in schema.values())
    print(f"Generated {len(schema)} tables / {total_cols} columns from schema {version}")
    print(f"  -> {SQL_OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "docs/schema/OpenDentalDocumentation25-4.xml")
